name: Build & Deploy Sanity Studio 🚀

on:
  push:
    branches:
      - main

jobs:
  sanity-deploy:
    name: Deploy Sanity Studio
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy Sanity Studio 🚀
        run: |
          npm ci
          npm run deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
